name: 'CogniSim GH Action'
description: 'Run a Cognisim test given an api key and a test id.'
author: 'CogniSim'

# Define your inputs here.
inputs:
  test-id:
    description: 'The test id to run.'
    required: true
  cognisim-device-url:
    description: 'The Cognisim device URL to use.'
    required: false
  cognisim-backend-url:
    description: 'The Cognisim backend URL to use.'
    required: false
  cognisim-action-url:
    description: 'The Cognisim action URL to use.'
    required: false

# Define your outputs here.
outputs:
  success:
    description: 'Whether or not the test fails.'

runs:
  using: node20
  main: dist/index.js
